"""客服多智能体示例的端口与地址配置。"""

TRIAGE_AGENT_PORT = 11001
ORDER_AGENT_PORT = 11002
POLICY_AGENT_PORT = 11003
LOGISTICS_AGENT_PORT = 11004

TRIAGE_AGENT_URL = f"http://localhost:{TRIAGE_AGENT_PORT}"
ORDER_AGENT_URL = f"http://localhost:{ORDER_AGENT_PORT}"
POLICY_AGENT_URL = f"http://localhost:{POLICY_AGENT_PORT}"
LOGISTICS_AGENT_URL = f"http://localhost:{LOGISTICS_AGENT_PORT}"
